app/views/general.py
# -*- coding: utf-8 -*-
__author__ = 'Martijn van Leeuwen'
__email__ = 'info@voc-electronics.com'
from flask import Blueprint, render_template, session, redirect, url_for, \
  request, flash, g, jsonify, abort
from app.utils import requires_login, request_wants_json
#from app.search import search as perform_search
from app.wifidomo_manager import verify_password

mod = Blueprint('general', __name__)

@mod.route('/')
def index():
  return render_template('index.html')


@mod.route('/login', methods=['GET', 'POST'])
def login():
  error = None
  if request.method == 'POST':

    if not verify_password(request.form['username'], request.form['password']):
      error = 'Invalid login credentials'
    else:
      session['logged_in'] = True
      flash('You were logged in')
      return redirect(url_for('general.index'))
  return render_template('login.html', error=error)


@mod.route('/logout')
def logout():
  session.pop('logged_in', None)
  flash('You were logged out')
  return redirect(url_for('general.login'))


@mod.route('/search/')
def search():
    q = request.args.get('q') or ''
    page = request.args.get('page', type=int) or 1
    results = None
    if q:
        results = perform_search(q, page=page)
        if results is None:
            abort(404)
    return render_template('general/search.html', results=results, q=q)

app/views/wifidomos.py
# -*- coding: utf-8 -*-
__author__ = 'Martijn van Leeuwen'
__email__ = 'info@voc-electronics.com'
from flask import Blueprint, render_template, session, redirect, url_for, \
  request, flash, g, jsonify, abort
from app.utils import requires_login, request_wants_json
from app.search import search as perform_search
from app.wifidomo_manager import verify_password

mod = Blueprint('wifidomos', __name__)

@mod.add('/add/', methods=['POST'])
@requires_login
def add_wifidomo():
  error = None
  location_id = None
  preview = None
  if 'location' in request.args:
    rv = Location.query.filter_by(slug=request.args['location']).first()
    if rv is not None:
      location_id = rv.id
  if request.method == 'POST':
    location_id_id = request.form.get('location_id', type=int)
    if 'preview' in request.form:
      preview = format_creole(request.form[ 'body' ])
    else:
      title = request.form['title']
      body = request.form['body']
      if not body:
        flash(u'Error: you have to enter a location')
      else:
        location = Location.query.get(location_id)
        if location is not None:
          # wifidomo = Wifidomo(g.user, title, body, location)
          # db_session.add(wifidomo)
          # db_session.commit()
          flash(u'Your wifidomo was added')
          return redirect(wifidomo.url)

    return render_template('wifidomos/new.html',
                           categories=Location.query.order_by(Location.name).all(),
                           active_category=location_id,
                           preview=preview)

app/templates/about.html
{% extends "layout.html" %}
{% block head %}
  {{ super() }}
  <style type=text/css>
    h1 { margin: 0 0 10px 0; background: url({{ url_for('static', filename='voc/logo_wifidomo.png') }}) no-repeat center; width 880px;height: 200px; }
    h1 span, p.tagline { display: none;
  </style>
  <script type=text/javascript>
    $(function() {
      $('h1').bind('mousedown contextmenu', function(event) {
        if (event.button != 2)
          return;
        var box = $('div.logohint');
        if (!box.is(':visible'))
          box.animate({'height': 'show', 'opacity': 'show'}, 100);
        event.preventDefault();
        event.returnValue = false;
        return false;
      });
    });
  </script>
{% endblock %}
{% block body_title %}
  {{ super() }}
  <p class=tagline>Mixing Open Source and Electronics.</p>
{% endblock %}

{% block body %}
  <pre>
    <span class=ig2>
      Some about text<br>
    </span>
  </pre>
{% endblock %}

app/templates/add.html
{% extends "layout.html" %}
{% block head %}
  {{ super() }}
  <style type=text/css>
    h1 { margin: 0 0 10px 0; background: url({{ url_for('static', filename='voc/logo_wifidomo.png') }}) no-repeat center; width 880px;height: 200px; }
    h1 span, p.tagline { display: none;
  </style>
  <script type=text/javascript>
    $(function() {
      $('h1').bind('mousedown contextmenu', function(event) {
        if (event.button != 2)
          return;
        var box = $('div.logohint');
        if (!box.is(':visible'))
          box.animate({'height': 'show', 'opacity': 'show'}, 100);
        event.preventDefault();
        event.returnValue = false;
        return false;
      });
    });
  </script>
{% endblock %}
{% block body_title %}
  {{ super() }}
  <p class=tagline>Mixing Open Source and Electronics.</p>
{% endblock %}

{% block body %}
  <div class="header">
    <h3 class="text-muted">Meterstanden</h3>
  </div>
  <pre>
    <span class=ig2>
      Add new:
      <div class="ig2">
        <form method="post" action="{{ url_for('add_entry') }}" class="meterstanden">
        <label for="elektra1" class="sr-only">Elektra I:</label>
        <input type="name" name="elektra1" id="elektra1" class="form-control" placeholder="Elektra I" required autofocus>
        <label for="elektra2" class="sr-only">Elektra II:</label>
        <input type="name" name="elektra2" id="elektra2" class="form-control" placeholder="Elektra II" required autofocus>
        <label for="water" class="sr-only">Water:</label>
        <input type="name" name="water" id="water" class="form-control" placeholder="Water" required autofocus>
        <label for="gas" class="sr-only">Gas:</label>
        <input type="name" name="gas" id="gas" class="form-control" placeholder="Gas" required autofocus>
        <label for="opname" class="sr-only">Opname datum:</label>
        <input type="name" name="opname" id="gas" class="form-control" placeholder="opname datum" required autofocus><br>
        <input type="submit" />
      </form>
      </div>
    </span>
  </pre>
{% endblock %}

app/templates/index.html
{% extends "layout.html" %}
{% block head %}
  {{ super() }}
  <style type=text/css>
    h1 { margin: 0 0 10px 0; background: url({{ url_for('static', filename='voc/logo_wifidomo.png') }}) no-repeat center; width 880px;height: 200px; }
    h1 span, p.tagline { display: none;
  </style>
  <script type="text/javascript">
        function zoom() {
            document.body.style.zoom = "50%"
        }
  </script>
  <script type=text/javascript>
    $(function() {
      $('h1').bind('mousedown contextmenu', function(event) {
        if (event.button != 2)
          return;
        var box = $('div.logohint');
        if (!box.is(':visible'))
          box.animate({'height': 'show', 'opacity': 'show'}, 100);
        event.preventDefault();
        event.returnValue = false;
        return false;
      });
    });
  </script>
{% endblock %}
{% block body_title %}
  {{ super() }}
  <p class=tagline>Mixing Open Source and Electronics.</p>
{% endblock %}

{% block body %}
 <body onload="zoom()">
  <div class="header">
    <h3 class="text-muted">Current active WiFiDomos:</h3>
  </div>
  <pre>
    <span class=ig2>
      Database entries:
      <ul class=overzicht>
        <li><em>Unbelievable.  No entries here so far</em>
      </ul>
    </span>
  </pre>
{% endblock %}

app/templates/layout.html
<!doctype html>
{% block head %}
<title>{% block title %}Welcome{% endblock %} | WiFiDomo Manager</title>
<meta charset=utf-8>
<!--<link rel=stylesheet type=text/css href="{{ url_for('static', filename='style-voc.css') }}">-->
<link rel=stylesheet type=text/css href="{{ url_for('static', filename='style.css') }}">
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
<script type=text/javascript
  src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
{% endblock %}

<div class=box>
  {% block body_title %}
    <h1><span>{{ self.title() }}</span></h1>
  {% endblock %}

  <p class=nav>
    <div class=metanav>
     <li>
    {% for item in nav.top %}
    <lu class="{{ 'active' if item.is_active else '' }}">
        <a href="{{ item.url }}">{{ item.label }}</a>
    </lu>
    {% endfor %}

    {% if not session.logged_in %}
      <a href="{{ url_for('general.login') }}">log in</a>
    {% else %}
      <a href="{{ url_for('general.logout') }}">log out</a>
    {% endif %}

    </li>
    </div>
   {% for message in get_flashed_messages() %}
    <div class=flash>{{ message }}</div>
  {% endfor %}
  </p>

  {% block body %}{% endblock %}

  <p class=footer>
    &copy; Copyright 2016 by <a href=http://www.voc-vanleeuwen.com/>V.O.C. Vanleeuwen Opensource Consultancy</a><br>
    Source based on code from the <a href=http://lucumr.pocoo.org/>Flask site</a>
  </p>
</div>


  <div class="menu">

  </div>

app/templates/list.html
list.html{% block head %}
  {{ super() }}
  <style type=text/css>
    h1 { margin: 0 0 10px 0; background: url({{ url_for('static', filename='voc/logo_wifidomo.png') }}) no-repeat center; width 880px;height: 200px; }
    h1 span, p.tagline { display: none;
  </style>
  <script type=text/javascript>
    $(function() {
      $('h1').bind('mousedown contextmenu', function(event) {
        if (event.button != 2)
          return;
        var box = $('div.logohint');
        if (!box.is(':visible'))
          box.animate({'height': 'show', 'opacity': 'show'}, 100);
        event.preventDefault();
        event.returnValue = false;
        return false;
      });
    });
  </script>
{% endblock %}
{% block body_title %}
  {{ super() }}
  <p class=tagline>Mixing Open Source and Electronics.</p>
{% endblock %}
{% block body %}
  <div class="header">
    <h3 class="text-muted">Meterstanden</h3>
  </div>
  <pre>
    <span class=ig2>
      Laaste entry in database:
      <ul class=overzicht>
      {% for entry in overzicht %}
        <li><h2>Opname datum: {{ entry.opname }}</h2><br> Electra1: {{ entry.elektra1 }}, Electra2: {{ entry.elektra2 }}, Gas: {{ entry.Gas }}, Water: {{ entry.Water }}
      {% else %}
        <li><em>Unbelievable.  No entries here so far</em>
      {% endfor %}
      </ul>
    </span>
  </pre>
{% endblock %}

app/templates/login.html
{% extends "layout.html" %}
{% block head %}
  {{ super() }}
   <script type="text/javascript">
        function zoom() {
            document.body.style.zoom = "50%"
        }
  </script>
  <style type="text/css">
    h1 { margin: 0 0 10px 0; background: url({{ url_for('static', filename='voc/logo_wifidomo.png') }}) no-repeat center; width 880px;height: 200px; }
    h1 span, p.tagline { display: none;
  </style>
  <script type=text/javascript>
    $(function() {
      $('h1').bind('mousedown contextmenu', function(event) {
        if (event.button != 2)
          return;
        var box = $('div.logohint');
        if (!box.is(':visible'))
          box.animate({'height': 'show', 'opacity': 'show'}, 100);
        event.preventDefault();
        event.returnValue = false;
        return false;
      });
    });
  </script>
{% endblock %}
{% block body %}
<body onload="zoom()">
  <h2>Login</h2>
  {% if error %}<p class=error><strong>Error:</strong> {{ error }}{% endif %}
  <form action="{{ url_for('general.login') }}" method=post>
    <dl>
      <dt>Username:
      <dd><input type=text name=username>
      <dt>Password:
      <dd><input type=password name=password>
      <dd><input type=submit value=Login>
    </dl>
  </form>
{% endblock %}

app/templates/overview.html
{% extends "layout.html" %}
{% block head %}
  {{ super() }}
  <style type=text/css>
    h1 { margin: 0 0 10px 0; background: url({{ url_for('static', filename='voc/logo_wifidomo.png') }}) no-repeat center; width 880px;height: 200px; }
    h1 span, p.tagline { display: none;
  </style>
  <script type=text/javascript>
    $(function() {
      $('h1').bind('mousedown contextmenu', function(event) {
        if (event.button != 2)
          return;
        var box = $('div.logohint');
        if (!box.is(':visible'))
          box.animate({'height': 'show', 'opacity': 'show'}, 100);
        event.preventDefault();
        event.returnValue = false;
        return false;
      });
    });
  </script>
{% endblock %}
{% block body_title %}
  {{ super() }}
  <p class=tagline>Current available WiFiDomos.</p>
{% endblock %}
{% block body %}
  <pre>
    <span class=ig2>
      <ul class=overzicht>
      {% for entry in overzicht %}
        <li>
          <h2>Unique ID: {{ entry.uid }}</h2><br>
          Network IP: {{ entry.ipaddress }},<br>
          MAC: {{ entry.network_mac }}, <br>
          Hostname: {{ entry.hostname }}, <br>
          Descrption: {{entry.description }}, <br>
          Location: {{ entry.location }}<br>
      {% else %}
        <li><em>Unbelievable.  No entries here so far</em>
      {% endfor %}
      </ul>
    </span>
  </pre>
{% endblock %}

app/templates/wifidomos/delete_location.html
{% extends "wifidomos/layout.html" %}
{% block title %}WiFiDomo Archive{% endblock %}
{% block body %}
  <h2>Delete Location “{{ location.name }}”</h2>
  <p>
    Do you want to delete this location?  And if yes, what should
    happen with the wifidomos in that location?
  <form action="" method=post>
    <p>
      <select name=move_to>
        <option value="">Delete WiFiDomos</option>
      {%- for location in other_locations %}
        <option value={{ location.id }}>Move to “{{ location.name }}”</option>
      {%- endfor %}
      </select>
    <p>
      <input type=submit value=Delete>
      <input type=submit name=cancel value=Cancel>
  </form>
{% endblock %}

app/templates/wifidomos/index.html
{% extends "wifidomos/layout.html" %}
{% block title %}WiFiDomos{% endblock %}
{% block body %}
  <p>
    Here we store the WiFiDomos.
  {% if g.user %}
  <p>
    You're signed in as “<span title="{{ g.user.openid }}">{{ g.user.name }}</span>”.
  {% else %}
  <p>
    In order to add new or modify WiFiDomos you need to be loged in.<br>
  {% endif %}
  <h2>WiFiDomos by Location</h2>
  <ul>
  {% for location in locations %}
    <li><a href="{{ location.url }}">{{ location.name }}</a> ({{ location.count }})
  {% endfor %}
  </ul>
  {% if recent %}
  <h2>Recently Added</h2>
  <ul>
  {% for wifidomo in recent %}
    <li><a href="{{ wifidomo.url }}">{{ wifidomo.hostname }}</a> in
      <a href="{{ wifidomo.location.url }}">{{ wifidomo.location.name }}</a>
  {% endfor %}
  </ul>
  {% endif %}
  {% if g.user.is_admin %}
  <h2>Admin Tools</h2>
  <ul>
    <li><a href="{{ url_for('.manage_locations') }}">Manage locations</a>
  </ul>
  {% endif %}
{% endblock %}

app/templates/wifidomos/layout.html
{% extends "layout.html" %}
{% block head %}
  {{ super() }}
  <link href="{{ url_for('.recent_feed') }}" rel="alternate" title="Recent Flask Snippets" type="application/atom+xml">
  <style type=text/css>
    h1 { background-image: url({{ url_for('static', filename='voc/logo_wifidomo.png') }}); }
  </style>
{% endblock %}
{% block body_title %}
  <h1><span>WiFiDomos:</span></h1>
{% endblock %}

app/templates/wifidomos/location.html
{% extends "wifidomos/layout.html" %}
{% block title %}{{ location.name }}{% endblock %}
{% block body %}
  <h2>{{ location.name }}</h2>
  {% if location.count > 3 %}
  <p>
    Here you can find all {{ category.count }} snippets of this
    category.  You can also
  {% else %}
    This category is pretty empty so far.  Why not
  {% endif %}
    <a href="{{ url_for('wifidomo.new',
      category=location.slug) }}">add a new one</a>.
  {% if locations %}
  <h3>WiFiDomos in this Location:</h3>
  <ul>
  {% for wifidomo in wifidomos %}
    <li><a href="{{ wifidomo.url }}">{{ wifidomo.title }}</a>
        <small>({{ wifidomo.pub_date|dateformat }})</small>
  {% endfor %}
  </ul>
  {% endif %}
{% endblock %}

app/templates/wifidomos/manage_locations.html
{% extends "wifidomos/layout.html" %}
{% block title %}WiFiDomo Archive{% endblock %}
{% block body %}
  <h2>Manage Locations</h2>
  {% if categories %}
  <form action="" method=post>
    <table>
      <tr>
        <th>Name
        <th>Slug
        <th>#
        <th>?
    {% for location in locations %}
      <tr>
        <td><input type=text name=name.{{ location.id }} value="{{ location.name }}" size=24>
        <td><input type=text name=slug.{{ location.id }} value="{{ location.slug }}" size=17>
        <td>{{ location.wifidomo.count() }}
        <td><a href="{{ url_for('.delete_location', id=location.id) }}">delete</a>
    {% endfor %}
    </table>
    <p class=actions>
      <input type=submit value="Update locations">
  </form>
  {% endif %}
  <form action="{{ url_for('.new_location') }}" method=post>
    <p>Or create a new location:
      <input type=text name=name size=40>
      <input type=submit value=Create>
  </form>
{% endblock %}

app/templates/wifidomos/new.html
{% extends "wifidomos/layout.html" %}
{% block head %}
  {{ super() }}
  <style type=text/css>
    h1 { background-image: url(/static/new-snippet.png); }
  </style>
{% endblock %}
{% block title %}New WiFiDomo{% endblock %}
{% block body %}
  <p>
    <small>Please fill in all details.</small>
  <form action="" method=post>
    <dl class=formlist>
      <dt>Title:
      <dd><input type=text name=title value="{{ request.form.title }}" size=40>
      <dt>Location:
      <dd>
        <select name=location>
        {% for location in locations %}
          <option{% if location.id == active_location %} selected{% endif
            %} value={{ location.id }}>{{ location.name }}</option>
        {% endfor %}
        </select>
    </dl>
    <p><textarea name=body cols=40 rows=20>{{ request.form.body }}</textarea>
    <p>
      <input type=submit value="Add WiFiDomo">
      <input type=submit name=preview value="Preview">
  </form>
  {% if preview %}
  <div id=preview>
    <h2>Preview</h2>
    {{ preview }}
  </div>
  {% endif %}
{% endblock %}

templates/about.html
{% extends "layout.html" %}
{% block head %}
  {{ super() }}
  <style type=text/css>
    h1 { margin: 0 0 10px 0; background: url({{ url_for('static', filename='voc/abstr_0.3.5.png') }}) no-repeat center; width 880px;height: 200px; }
    h1 span, p.tagline { display: none;
  </style>
  <script type=text/javascript>
    $(function() {
      $('h1').bind('mousedown contextmenu', function(event) {
        if (event.button != 2)
          return;
        var box = $('div.logohint');
        if (!box.is(':visible'))
          box.animate({'height': 'show', 'opacity': 'show'}, 100);
        event.preventDefault();
        event.returnValue = false;
        return false;
      });
    });
  </script>
{% endblock %}
{% block body_title %}
  {{ super() }}
  <p class=tagline>Mixing Open Source and Electronics.</p>
{% endblock %}

{% block body %}
  <pre>
    <span class=ig2>
      Some about text<br>
    </span>
  </pre>
{% endblock %}

templates/add.html
{% extends "layout.html" %}
{% block head %}
  {{ super() }}
  <style type=text/css>
    h1 { margin: 0 0 10px 0; background: url({{ url_for('static', filename='voc/abstr_0.3.5.png') }}) no-repeat center; width 880px;height: 200px; }
    h1 span, p.tagline { display: none;
  </style>
  <script type=text/javascript>
    $(function() {
      $('h1').bind('mousedown contextmenu', function(event) {
        if (event.button != 2)
          return;
        var box = $('div.logohint');
        if (!box.is(':visible'))
          box.animate({'height': 'show', 'opacity': 'show'}, 100);
        event.preventDefault();
        event.returnValue = false;
        return false;
      });
    });
  </script>
{% endblock %}
{% block body_title %}
  {{ super() }}
  <p class=tagline>Mixing Open Source and Electronics.</p>
{% endblock %}

{% block body %}
  <div class="header">
    <h3 class="text-muted">Meterstanden</h3>
  </div>
  <pre>
    <span class=ig2>
      Add new:
      <div class="ig2">
        <form method="post" action="{{ url_for('add_entry') }}" class="meterstanden">
        <label for="elektra1" class="sr-only">Elektra I:</label>
        <input type="name" name="elektra1" id="elektra1" class="form-control" placeholder="Elektra I" required autofocus>
        <label for="elektra2" class="sr-only">Elektra II:</label>
        <input type="name" name="elektra2" id="elektra2" class="form-control" placeholder="Elektra II" required autofocus>
        <label for="water" class="sr-only">Water:</label>
        <input type="name" name="water" id="water" class="form-control" placeholder="Water" required autofocus>
        <label for="gas" class="sr-only">Gas:</label>
        <input type="name" name="gas" id="gas" class="form-control" placeholder="Gas" required autofocus>
        <label for="opname" class="sr-only">Opname datum:</label>
        <input type="name" name="opname" id="gas" class="form-control" placeholder="opname datum" required autofocus><br>
        <input type="submit" />
      </form>
      </div>
    </span>
  </pre>
{% endblock %}

templates/index.html
{% extends "layout.html" %}
{% block head %}
  {{ super() }}
  <style type=text/css>
    h1 { margin: 0 0 10px 0; background: url({{ url_for('static', filename='voc/abstr_0.3.5.png') }}) no-repeat center; width 880px;height: 200px; }
    h1 span, p.tagline { display: none;
  </style>
  <script type=text/javascript>
    $(function() {
      $('h1').bind('mousedown contextmenu', function(event) {
        if (event.button != 2)
          return;
        var box = $('div.logohint');
        if (!box.is(':visible'))
          box.animate({'height': 'show', 'opacity': 'show'}, 100);
        event.preventDefault();
        event.returnValue = false;
        return false;
      });
    });
  </script>
{% endblock %}
{% block body_title %}
  {{ super() }}
  <p class=tagline>Mixing Open Source and Electronics.</p>
{% endblock %}

{% block body %}
  <div class="header">
    <h3 class="text-muted">Meterstanden</h3>
  </div>
  <pre>
    <span class=ig2>
      Laaste entry in database:
      <ul class=overzicht>
      {% for entry in overzicht %}
        <li><h2>Opname datum: {{ entry.opname }}</h2><br> Electra1: {{ entry.elektra1 }}, Electra2: {{ entry.elektra2 }}, Gas: {{ entry.Gas }}, Water: {{ entry.Water }}
      {% else %}
        <li><em>Unbelievable.  No entries here so far</em>
      {% endfor %}
      </ul>
    </span>
  </pre>
{% endblock %}

templates/layout.html
<!doctype html>
{% block head %}
<title>{% block title %}Welcome{% endblock %} | Vanleeuwen Opensource Consultancy</title>
<meta charset=utf-8>
<!--<link rel=stylesheet type=text/css href="{{ url_for('static', filename='style-voc.css') }}">-->
<link rel=stylesheet type=text/css href="{{ url_for('static', filename='style.css') }}">
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
<script type=text/javascript
  src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
{% endblock %}

<div class=box>
  {% block body_title %}
    <h1><span>{{ self.title() }}</span></h1>
  {% endblock %}

  <p class=nav>
    <div class=metanav>
     <li>
    {% for item in nav.top %}
    <lu class="{{ 'active' if item.is_active else '' }}">
        <a href="{{ item.url }}">{{ item.label }}</a>
    </lu>
    {% endfor %}

    {% if not session.logged_in %}
      <a href="{{ url_for('login') }}">log in</a>
    {% else %}
      <a href="{{ url_for('logout') }}">log out</a>
    {% endif %}

    </li>
    </div>
   {% for message in get_flashed_messages() %}
    <div class=flash>{{ message }}</div>
  {% endfor %}
  </p>

  {% block body %}{% endblock %}

  <p class=footer>
    &copy; Copyright 2016 by <a href=http://www.voc-vanleeuwen.com/>V.O.C. Vanleeuwen Opensource Consultancy</a><br>
    Source based on code from the <a href=http://lucumr.pocoo.org/>Flask site</a>
  </p>
</div>


  <div class="menu">

  </div>

templates/list.html
list.html{% block head %}
  {{ super() }}
  <style type=text/css>
    h1 { margin: 0 0 10px 0; background: url({{ url_for('static', filename='voc/abstr_0.3.5.png') }}) no-repeat center; width 880px;height: 200px; }
    h1 span, p.tagline { display: none;
  </style>
  <script type=text/javascript>
    $(function() {
      $('h1').bind('mousedown contextmenu', function(event) {
        if (event.button != 2)
          return;
        var box = $('div.logohint');
        if (!box.is(':visible'))
          box.animate({'height': 'show', 'opacity': 'show'}, 100);
        event.preventDefault();
        event.returnValue = false;
        return false;
      });
    });
  </script>
{% endblock %}
{% block body_title %}
  {{ super() }}
  <p class=tagline>Mixing Open Source and Electronics.</p>
{% endblock %}
{% block body %}
  <div class="header">
    <h3 class="text-muted">Meterstanden</h3>
  </div>
  <pre>
    <span class=ig2>
      Laaste entry in database:
      <ul class=overzicht>
      {% for entry in overzicht %}
        <li><h2>Opname datum: {{ entry.opname }}</h2><br> Electra1: {{ entry.elektra1 }}, Electra2: {{ entry.elektra2 }}, Gas: {{ entry.Gas }}, Water: {{ entry.Water }}
      {% else %}
        <li><em>Unbelievable.  No entries here so far</em>
      {% endfor %}
      </ul>
    </span>
  </pre>
{% endblock %}

templates/login.html
{% extends "layout.html" %}
{% block head %}
  {{ super() }}
  <style type=text/css>
    h1 { margin: 0 0 10px 0; background: url({{ url_for('static', filename='voc/abstr_0.3.5.png') }}) no-repeat center; width 880px;height: 200px; }
    h1 span, p.tagline { display: none;
  </style>
  <script type=text/javascript>
    $(function() {
      $('h1').bind('mousedown contextmenu', function(event) {
        if (event.button != 2)
          return;
        var box = $('div.logohint');
        if (!box.is(':visible'))
          box.animate({'height': 'show', 'opacity': 'show'}, 100);
        event.preventDefault();
        event.returnValue = false;
        return false;
      });
    });
  </script>
{% endblock %}
{% block body %}
  <h2>Login</h2>
  {% if error %}<p class=error><strong>Error:</strong> {{ error }}{% endif %}
  <form action="{{ url_for('login') }}" method=post>
    <dl>
      <dt>Username:
      <dd><input type=text name=username>
      <dt>Password:
      <dd><input type=password name=password>
      <dd><input type=submit value=Login>
    </dl>
  </form>
{% endblock %}

templates/overview.html
{% extends "layout.html" %}
{% block head %}
  {{ super() }}
  <style type=text/css>
    h1 { margin: 0 0 10px 0; background: url({{ url_for('static', filename='voc/abstr_0.3.5.png') }}) no-repeat center; width 880px;height: 200px; }
    h1 span, p.tagline { display: none;
  </style>
  <script type=text/javascript>
    $(function() {
      $('h1').bind('mousedown contextmenu', function(event) {
        if (event.button != 2)
          return;
        var box = $('div.logohint');
        if (!box.is(':visible'))
          box.animate({'height': 'show', 'opacity': 'show'}, 100);
        event.preventDefault();
        event.returnValue = false;
        return false;
      });
    });
  </script>
{% endblock %}
{% block body_title %}
  {{ super() }}
  <p class=tagline>Mixing Open Source and Electronics.</p>
{% endblock %}
{% block body %}
  <div class="header">
    <h3 class="text-muted">Meterstanden</h3>
  </div>
  <pre>
    <span class=ig2>
      Laaste entry in database:
      <ul class=overzicht>
      {% for entry in overzicht %}
        <li><h2>Opname datum: {{ entry.opname }}</h2><br> Electra1: {{ entry.elektra1 }}, Electra2: {{ entry.elektra2 }}, Gas: {{ entry.Gas }}, Water: {{ entry.Water }}
      {% else %}
        <li><em>Unbelievable.  No entries here so far</em>
      {% endfor %}
      </ul>
    </span>
  </pre>
{% endblock %}